// User types
export const userTypes = {
  SET_USER: 'SET_USER',
  RELOAD_USER: 'RELOAD_USER',
  CLEAR_USER: 'CLEAR_USER',
  SET_USER_LIKES: 'SET_USER_LIKES',
  SET_USER_FOLLOWING: 'SET_USER_FOLLOWING',
  ADD_USER_FOLLOWING: 'ADD_USER_FOLLOWING',
  REMOVE_USER_FOLLOWING: 'REMOVE_USER_FOLLOWING',
  ADD_LIKE: 'ADD_LIKE',
  REMOVE_LIKE: 'REMOVE_LIKE',
  ADD_COMMENT: 'ADD_COMMENT',
  UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
  UPDATE_COVER_PICTURE: 'UPDATE_COVER_PICTURE',
};

// Posts types
export const postsTypes = {
  SET_POSTS: 'SET_POSTS',
  SELECT_POST: 'SELECT_POST',
  CLEAR_POSTS: 'CLEAR_POSTS',
  ADD_POST: 'ADD_POST',
  UPDATE_POST: 'UPDATE_POST',
};

// Comments types
export const commentsTypes = {
  SET_POST_COMMENTS: 'SET_POST_COMMENTS',
  CLEAR_POST_COMMENTS: 'CLEAR_POST_COMMENTS',
  ADD_COMMENT: 'ADD_COMMENT',
};

// Hashtag types
export const hashtagsTypes = {
  SET_TRENDING: 'SET_TRENDING',
  CLEAR_TRENDING: 'CLEAR_TRENDING',
};
